version: 2
jobs:
  build:
    docker: 
      - image: circleci/node:8.11-browsers
    steps:
      - checkout
      - run: 
          name: Install Dependencies
          command: yarn && cd angular-demo && yarn && cd ../react-demo && yarn
      - run:
          name: Test
          command: yarn test
      - run:
          name: Build Package
          command: yarn build
      - run:
          name: Verify Artifacts
          command: yarn test:build